# Generated by Django 5.2.7 on 2026-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(max_length=100, verbose_name='职位/头衔')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地')),
                ('summary', models.TextField(verbose_name='个人简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('degree', models.CharField(max_length=100, verbose_name='学位')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '教育背景',
                'verbose_name_plural': '教育背景',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='公司/组织')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期 (至今为空)')),
                ('description', models.TextField(verbose_name='工作描述')),
                ('is_current', models.BooleanField(default=False, verbose_name='至今')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('role', models.CharField(max_length=100, verbose_name='担任角色')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('technologies', models.CharField(blank=True, max_length=200, null=True, verbose_name='使用技术')),
                ('link', models.URLField(blank=True, null=True, verbose_name='项目链接')),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='技能名称')),
                ('level', models.IntegerField(default=50, verbose_name='熟练度(0-100)')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['-level'],
            },
        ),
    ]
