# Generated by Django 5.2.7 on 2026-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('issuer', models.CharField(max_length=100, verbose_name='颁发机构')),
                ('date', models.DateField(verbose_name='颁发日期')),
                ('link', models.URLField(blank=True, null=True, verbose_name='证书链接')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='语言')),
                ('proficiency', models.CharField(max_length=50, verbose_name='熟练程度')),
            ],
            options={
                'verbose_name': '语言能力',
                'verbose_name_plural': '语言能力',
            },
        ),
    ]
