# Generated by Django 5.2.7 on 2026-02-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_certificate_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='技术名称')),
                ('level', models.IntegerField(default=50, verbose_name='熟练度(0-100)')),
                ('icon', models.CharField(blank=True, default='⚡', max_length=50, null=True, verbose_name='图标(Emoji/Class)')),
            ],
            options={
                'verbose_name': '技术栈',
                'verbose_name_plural': '技术栈',
                'ordering': ['-level'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level'], 'verbose_name': '技能/关键词', 'verbose_name_plural': '技能/关键词'},
        ),
    ]
