# Generated by Django 5.2.7 on 2026-02-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_techstack_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['-years'], 'verbose_name': '技术栈', 'verbose_name_plural': '技术栈'},
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='level',
        ),
        migrations.AddField(
            model_name='techstack',
            name='years',
            field=models.IntegerField(default=1, verbose_name='经验年限(年)'),
        ),
    ]
