# Generated by Django 5.2.7 on 2026-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_techstack_options_remove_techstack_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=10, null=True, verbose_name='性别'),
        ),
    ]
