# Generated by Django 5.2.7 on 2026-03-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_basicinfo_age_basicinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='summary_experience',
            field=models.TextField(blank=True, null=True, verbose_name='工作经验'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_management',
            field=models.TextField(blank=True, null=True, verbose_name='团队管理'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_skills',
            field=models.TextField(blank=True, null=True, verbose_name='专业能力'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介(旧版)'),
        ),
    ]
