# Generated by Django 5.2.7 on 2026-03-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_basicinfo_summary_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg_description',
            field=models.TextField(blank=True, null=True, verbose_name='项目背景'),
        ),
        migrations.AddField(
            model_name='project',
            name='duty_description',
            field=models.TextField(blank=True, null=True, verbose_name='项目职责'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_description',
            field=models.TextField(blank=True, null=True, verbose_name='项目成果'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_description',
            field=models.TextField(blank=True, null=True, verbose_name='解决方案'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='项目描述(旧版)'),
        ),
    ]
