# Generated by Django 5.2.7 on 2026-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_project_bg_description_project_duty_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['order', 'major_category', 'minor_category', 'id'], 'verbose_name': '技术栈', 'verbose_name_plural': '技术栈'},
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='years',
        ),
        migrations.AddField(
            model_name='techstack',
            name='experience',
            field=models.CharField(default='1年', max_length=50, verbose_name='经验年限'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='major_category',
            field=models.CharField(default='未分类', max_length=100, verbose_name='大分类'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='minor_category',
            field=models.CharField(default='未分类', max_length=100, verbose_name='小分类'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='name',
            field=models.CharField(max_length=100, verbose_name='技能内容'),
        ),
    ]
