# Generated by Django 5.2.7 on 2026-03-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_techstack_options_remove_techstack_years_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-start_date'], 'verbose_name': '项目经历', 'verbose_name_plural': '项目经历'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='显示顺序(从小到大)'),
        ),
    ]
