# Generated by Django 5.2.7 on 2026-03-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_project_options_project_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
