# Generated by Django 5.2.7 on 2026-08-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地(English)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='location_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地(日本語)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介(English)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_experience_en',
            field=models.TextField(blank=True, null=True, verbose_name='工作经验(English)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_experience_ja',
            field=models.TextField(blank=True, null=True, verbose_name='工作经验(日本語)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_ja',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介(日本語)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_management_en',
            field=models.TextField(blank=True, null=True, verbose_name='团队管理(English)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_management_ja',
            field=models.TextField(blank=True, null=True, verbose_name='团队管理(日本語)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_skills_en',
            field=models.TextField(blank=True, null=True, verbose_name='专业能力(English)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary_skills_ja',
            field=models.TextField(blank=True, null=True, verbose_name='专业能力(日本語)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位/头衔(English)'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='title_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位/头衔(日本語)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='颁发机构(English)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='颁发机构(日本語)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='证书名称(English)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='证书名称(日本語)'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学位(English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学位(日本語)'),
        ),
        migrations.AddField(
            model_name='education',
            name='major_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业(English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='major_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业(日本語)'),
        ),
        migrations.AddField(
            model_name='education',
            name='school_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学校(English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='school_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学校(日本語)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司/组织(English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司/组织(日本語)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='工作描述(English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='工作描述(日本語)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位(English)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='bg_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='项目背景(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='bg_description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='项目背景(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='项目描述(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='项目描述(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='duty_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='项目职责(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='duty_description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='项目职责(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='项目成果(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='项目成果(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='担任角色(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='担任角色(日本語)'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='解决方案(English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='解决方案(日本語)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分类(English)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_ja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分类(日本語)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='major_category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大分类(English)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='major_category_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大分类(日本語)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='minor_category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='小分类(English)'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='minor_category_ja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='小分类(日本語)'),
        ),
    ]
