# Generated by Django 5.2.7 on 2026-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作品简介')),
                ('work_type', models.CharField(choices=[('audio', '音频作品'), ('video', '演出视频')], default='audio', max_length=10, verbose_name='类型')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/covers/', verbose_name='封面图片')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/audio/', verbose_name='音频文件')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='视频链接(如B站)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '音乐作品',
                'verbose_name_plural': '音乐作品',
                'ordering': ['-created_at'],
            },
        ),
    ]
