# Generated by Django 5.2.7 on 2026-03-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicwork',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='music/video/', verbose_name='视频文件(直接上传)'),
        ),
    ]
