# Generated by Django 5.2.7 on 2026-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicwork_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicwork',
            name='work_type',
            field=models.CharField(choices=[('audio', '音频作品'), ('video', '演出视频'), ('photo', '演出照片')], default='audio', max_length=10, verbose_name='类型'),
        ),
    ]
