# Generated by Django 5.2.7 on 2026-08-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_musicwork_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicwork',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='作品简介(English)'),
        ),
        migrations.AddField(
            model_name='musicwork',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='作品简介(日本語)'),
        ),
        migrations.AddField(
            model_name='musicwork',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='作品名称(English)'),
        ),
        migrations.AddField(
            model_name='musicwork',
            name='title_ja',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='作品名称(日本語)'),
        ),
    ]
